# Generated by Django 2.0.2 on 2018-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_register',
            name='proof_img',
            field=models.ImageField(default='null', upload_to='img'),
            preserve_default=False,
        ),
    ]
