# Generated by Django 2.0.2 on 2018-04-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180404_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
